version: 2

references:

  xcode_version: &xcode_version  "10.0.0"

  container_config: &container_config
    macos:
      xcode: *xcode_version

  build_app: &build_app
    run:
      name: Build app
      command: source ci/scripts/build.sh

  bundler_config: &bundler_config
    run:
      name: Configure bundler
      command: source ./ci/scripts/bundler_config.sh

  install_ruby: &install_ruby
    run:
      name: Configure Ruby dependencies
      command: source ./ci/scripts/install_ruby.sh

  fastlane_config: &fastlane_config
    run:
      name: Configure Fastlane environment variables
      command: source ./ci/scripts/fastlane_config.sh
  
  test_app: &test_app
    run:
      name: Test project
      command: source ./ci/scripts/test.sh
  
  install: &install
    run:
      name: Install dependencies
      command: source ./ci/scripts/install.sh
  
  keychain_add: &keychain_add
    run:
      name: Create keychain & Add certificates
      command: source ./ci/scripts/keychain_add.sh
      environment:
        CERTIFICATES_PATH: ./ci/cert
        KEYCHAIN_NAME: ios-app.keychain

  keychain_remove: &keychain_remove
    run:
      name: Remove keychain
      command: source ./ci/scripts/keychain_remove.sh
      environment:
        KEYCHAIN_NAME: ios-app.keychain

  git_config: &git_config
    run:
      name: Configure github
      command: source ./ci/scripts/git_config.sh

  create_documentation: &create_documentation
    run:
      name: Generate documentation
      command: source ci/scripts/documentation.sh
      environment:
        DOCUMENTATION_DESTINATION: development/code-documentation/
  
  create_coverage: &create_coverage
    run:
      name: Generate coverage
      command: source ci/scripts/coverage.sh
      environment:
        COVERAGE_DESTINATION: development/coverage/
        TEST_REPORT_DESTINATION: development/test-report/

  update_cache: &update_cache
    run:
      name: Update cache gh-pages
      command: source ci/scripts/update_cache.sh
  
  release_app: &release_app
    run:
      name: Release app
      command: source ci/scripts/release.sh

  store_ipa: &store_ipa
    store_artifacts:
      path: ./$XCODE_SCHEME_DEMO.ipa
  
  pod_trunk: &pod_trunk
    run:
      name: Update cocoapods
      command: source ./ci/scripts/pod_trunk_push.sh
      environment:
        SCRIPT_PATH: ./ci/scripts

jobs:

  build:
    <<: *container_config
    steps:
      - checkout
      - *build_app

  test:
    <<: *container_config
    steps:
      - checkout
      - *bundler_config
      - *install_ruby
      - *fastlane_config
      - *test_app

  documentation:
    <<: *container_config
    steps:
      - checkout
      - *bundler_config
      - *install
      - *git_config
      - *create_documentation

  coverage:
    <<: *container_config
    steps:
      - checkout
      - *bundler_config
      - *install
      - *fastlane_config
      - *git_config
      - *test_app
      - *create_coverage

  release:
    <<: *container_config
    steps:
      - checkout
      - *bundler_config
      - *install
      - *fastlane_config
      - *keychain_add
      - *git_config
      - *release_app
      - *store_ipa
      - *keychain_remove
      # - *pod_trunk

  update_cache:
    <<: *container_config
    steps:
      - checkout
      - *bundler_config
      - *install
      - *git_config
      - *update_cache

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - documentation:
          requires:
            - test
          filters:
            branches:
              only:
                - master
                - develop
      - coverage:
          requires:
            - test
          filters:
            branches:
              only:
                - master
                - develop
      - release:
          requires:
            - coverage
            - documentation
          filters:
            branches:
              only:
                - master
      - update_cache:
          requires:
            - coverage
            - documentation
          filters:
            branches:
              only:
                - master
                - develop
